# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 04:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('gateway', models.GenericIPAddressField(verbose_name='网关')),
                ('network', models.GenericIPAddressField(verbose_name='网络号')),
                ('mask', models.CharField(blank='', default='', max_length=20, null=True, verbose_name='掩码')),
                ('system', models.CharField(blank='', default='', max_length=64, null=True, verbose_name='应用系统')),
                ('apply_person', models.CharField(blank='', default='', max_length=64, null=True, verbose_name='申请人')),
                ('state', models.CharField(choices=[('已分配', '已分配'), ('未分配', '未分配')], max_length=20, verbose_name='状态')),
                ('desc', models.CharField(blank='', default='', max_length=64, null=True, verbose_name='描述')),
                ('apply_time', models.DateField(default=datetime.datetime(2018, 3, 4, 12, 38, 13, 264000), verbose_name='申请时间')),
            ],
        ),
        migrations.CreateModel(
            name='IPRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ip', models.GenericIPAddressField(verbose_name='开始IP')),
                ('end_ip', models.GenericIPAddressField(verbose_name='结束IP')),
                ('use_ip', models.CharField(blank='', default='', max_length=20, null=True, verbose_name='已使用IP数')),
                ('left_ip', models.CharField(blank='', default='', max_length=20, null=True, verbose_name='未使用IP数')),
                ('desc', models.CharField(blank='', default='', max_length=20, null=True, verbose_name='描述')),
                ('create_time', models.DateField(default=datetime.datetime(2018, 3, 4, 12, 38, 13, 265000), verbose_name='创建时间')),
            ],
        ),
    ]
